In [1]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import os
from tensorflow import keras

# cargar los datos
# df = pd.read_csv("../../new/datasets/unbalanced_30000.csv", header=None)
# df = pd.read_csv("../../new/datasets/unbalanced_15000.csv", header=None)
df = pd.read_csv("../../new/datasets/unbalanced.csv", header=None)

# separar las características (X) y la etiqueta (y)
X = df.drop(columns=343, axis=1)
# y = df.iloc[343]
y = df.iloc[:, 343]

# codificar la etiqueta (y)
encoder = LabelEncoder()
y = encoder.fit_transform(y)

# dividir el conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5, stratify=y)


In [2]:
column_names = ['wl_' + str(i) for i in range(336, 1021, 2)]

In [3]:
X_test.columns = column_names

In [4]:
# X_test['class'] = y_test

In [5]:
# X_test.to_csv('./test_stars.csv', index= False)

In [6]:
y_test

array([2, 1, 1, 1, 0, 2, 2, 2, 1, 1, 2, 1, 1, 0, 1, 2, 2, 1, 2, 2, 1, 0,
       2, 1, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 0, 1, 2, 2, 2, 0,
       0, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 0,
       0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 0, 0, 2, 2, 1, 2, 1,
       0, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 1,
       2, 1, 2, 2, 2, 1, 2, 2, 0, 2, 2, 0, 1, 2, 2, 2, 1, 2, 2, 2, 2, 0,
       2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 0,
       2, 2, 2, 2, 0, 1, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1,
       0, 0, 2, 1, 2, 1, 2, 1, 1, 2, 2, 0, 2, 2, 2, 0, 1, 2, 1, 2, 2, 2,
       1, 2, 1, 0, 2, 2, 2, 2, 1, 0, 2, 2, 2, 2, 1, 0, 2, 2, 1, 2, 1, 2,
       1, 2, 1, 2, 1, 2, 0, 1, 2, 1, 2, 1, 0, 1, 0, 2, 2, 1, 2, 2, 0, 2,
       2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2,

# Prueba 1

In [7]:
# crear el modelo
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    # tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='relu'),
    # tf.keras.layers.Dropout(0.2),
    # tf.keras.layers.Dense(30, activation='relu'),
    # tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(3, activation='softmax')
])

# compilar el modelo
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [8]:
# entrenar el modelo
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))


Epoch 1/100
50/50 [==============================] - 1s 6ms/step - loss: 0.6367 - accuracy: 0.7038 - val_loss: 0.5150 - val_accuracy: 0.8304
Epoch 2/100
50/50 [==============================] - 0s 2ms/step - loss: 0.4170 - accuracy: 0.8589 - val_loss: 0.4528 - val_accuracy: 0.8532
Epoch 3/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3710 - accuracy: 0.8791 - val_loss: 0.4260 - val_accuracy: 0.8532
Epoch 4/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3445 - accuracy: 0.8873 - val_loss: 0.3954 - val_accuracy: 0.8608
Epoch 5/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3242 - accuracy: 0.8886 - val_loss: 0.4009 - val_accuracy: 0.8329
Epoch 6/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3191 - accuracy: 0.8911 - val_loss: 0.3757 - val_accuracy: 0.8709
Epoch 7/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3061 - accuracy: 0.9000 - val_loss: 0.3791 - val_accuracy: 0.8633
Epoch 8/100
5

# Classify all Red Giants

In [9]:
df_rg = df = pd.read_csv("../../new/normalized/RG.csv", header=None)

import numpy as np
from sklearn.metrics import confusion_matrix

# predecir las probabilidades para los datos de prueba
y_probs = model.predict(df_rg)
y_pred = np.argmax(y_probs, axis=-1)
cm = confusion_matrix([2 for _ in range(69146)], y_pred)
print(cm)


2161/2161 [==============================] - 2s 861us/step
[[    0     0     0]
 [    0     0     0]
 [   70   585 68491]]


In [10]:
import numpy as np
from sklearn.metrics import confusion_matrix

# predecir las probabilidades para los datos de prueba
y_probs = model.predict(X_test)
y_pred = np.argmax(y_probs, axis=-1)
cm = confusion_matrix(y_test, y_pred)
print(cm)


13/13 [==============================] - 0s 1ms/step
[[ 32   2   6]
 [  6  88  21]
 [  1   5 234]]


In [12]:
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred, digits=4)
print(report)

              precision    recall  f1-score   support

           0     0.8205    0.8000    0.8101        40
           1     0.9263    0.7652    0.8381       115
           2     0.8966    0.9750    0.9341       240

    accuracy                         0.8962       395
   macro avg     0.8811    0.8467    0.8608       395
weighted avg     0.8975    0.8962    0.8936       395



In [13]:
from sklearn.metrics import cohen_kappa_score, classification_report

print("Cohen's kappa: ", cohen_kappa_score(y_test, y_pred))

Cohen's kappa:  0.799814585908529


# Save model

In [14]:
# Save the model to a single file
model.save( './rna_unbalance_test1.keras', save_format='keras_v3')

# Prueba 2

In [15]:
# crear el modelo
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(20, activation='relu'),
    # tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(20, activation='relu'),
    # tf.keras.layers.Dropout(0.2),
    # tf.keras.layers.Dense(30, activation='relu'),
    # tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(3, activation='softmax')
])

# compilar el modelo
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# entrenar el modelo
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))


Epoch 1/100
50/50 [==============================] - 1s 6ms/step - loss: 0.6514 - accuracy: 0.7544 - val_loss: 0.5284 - val_accuracy: 0.8253
Epoch 2/100
50/50 [==============================] - 0s 2ms/step - loss: 0.4202 - accuracy: 0.8627 - val_loss: 0.4310 - val_accuracy: 0.8405
Epoch 3/100
50/50 [==============================] - 0s 3ms/step - loss: 0.3526 - accuracy: 0.8772 - val_loss: 0.4033 - val_accuracy: 0.8557
Epoch 4/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3332 - accuracy: 0.8854 - val_loss: 0.3986 - val_accuracy: 0.8658
Epoch 5/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3107 - accuracy: 0.8918 - val_loss: 0.3827 - val_accuracy: 0.8481
Epoch 6/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3006 - accuracy: 0.9038 - val_loss: 0.3720 - val_accuracy: 0.8608
Epoch 7/100
50/50 [==============================] - 0s 2ms/step - loss: 0.2907 - accuracy: 0.9038 - val_loss: 0.3637 - val_accuracy: 0.8658
Epoch 8/100
5

In [16]:
import numpy as np
from sklearn.metrics import confusion_matrix

# predecir las probabilidades para los datos de prueba
y_probs = model.predict(X_test)
y_pred = np.argmax(y_probs, axis=-1)
cm = confusion_matrix(y_test, y_pred)
print(cm)


13/13 [==============================] - 0s 1ms/step
[[ 35   2   3]
 [  6  91  18]
 [  2  10 228]]


In [17]:
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred, digits=4)
print(report)

              precision    recall  f1-score   support

           0     0.8140    0.8750    0.8434        40
           1     0.8835    0.7913    0.8349       115
           2     0.9157    0.9500    0.9325       240

    accuracy                         0.8962       395
   macro avg     0.8710    0.8721    0.8703       395
weighted avg     0.8960    0.8962    0.8951       395



In [18]:
# Save the model to a single file
model.save( './rna_unbalance_test2.keras', save_format='keras_v3')

# Prueba 3

In [20]:
# crear el modelo
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(20, activation='relu'),
    # tf.keras.layers.Dropout(0.2),
    # tf.keras.layers.Dense(20, activation='relu'),
    # tf.keras.layers.Dropout(0.2),
    # tf.keras.layers.Dense(30, activation='relu'),
    # tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(3, activation='softmax')
])

# compilar el modelo
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# entrenar el modelo
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))


Epoch 1/100
50/50 [==============================] - 1s 6ms/step - loss: 0.5754 - accuracy: 0.7785 - val_loss: 0.4636 - val_accuracy: 0.8177
Epoch 2/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3820 - accuracy: 0.8608 - val_loss: 0.4253 - val_accuracy: 0.8532
Epoch 3/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3546 - accuracy: 0.8715 - val_loss: 0.4165 - val_accuracy: 0.8557
Epoch 4/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3366 - accuracy: 0.8829 - val_loss: 0.4097 - val_accuracy: 0.8405
Epoch 5/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3283 - accuracy: 0.8886 - val_loss: 0.3837 - val_accuracy: 0.8734
Epoch 6/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3184 - accuracy: 0.8905 - val_loss: 0.3807 - val_accuracy: 0.8430
Epoch 7/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3015 - accuracy: 0.9006 - val_loss: 0.3875 - val_accuracy: 0.8658
Epoch 8/100
5

In [21]:

import numpy as np
from sklearn.metrics import confusion_matrix

# predecir las probabilidades para los datos de prueba
y_probs = model.predict(X_test)
y_pred = np.argmax(y_probs, axis=-1)
cm = confusion_matrix(y_test, y_pred)
print(cm)

13/13 [==============================] - 0s 1ms/step
[[ 34   2   4]
 [  4  91  20]
 [  2  12 226]]


In [22]:
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred, digits=4)
print(report)

              precision    recall  f1-score   support

           0     0.8500    0.8500    0.8500        40
           1     0.8667    0.7913    0.8273       115
           2     0.9040    0.9417    0.9224       240

    accuracy                         0.8886       395
   macro avg     0.8736    0.8610    0.8666       395
weighted avg     0.8877    0.8886    0.8874       395



In [23]:
# Save the model to a single file
model.save( './rna_unbalance_test3.keras', save_format='keras_v3')

# Prueba 4

In [24]:
# crear el modelo
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    # tf.keras.layers.Dropout(0.2),
    # tf.keras.layers.Dense(20, activation='relu'),
    # tf.keras.layers.Dropout(0.2),
    # tf.keras.layers.Dense(30, activation='relu'),
    # tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(3, activation='softmax')
])

# compilar el modelo
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# entrenar el modelo
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/100
50/50 [==============================] - 1s 6ms/step - loss: 0.6012 - accuracy: 0.7601 - val_loss: 0.4932 - val_accuracy: 0.8152
Epoch 2/100
50/50 [==============================] - 0s 2ms/step - loss: 0.4028 - accuracy: 0.8608 - val_loss: 0.4311 - val_accuracy: 0.8582
Epoch 3/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3595 - accuracy: 0.8791 - val_loss: 0.4145 - val_accuracy: 0.8684
Epoch 4/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3345 - accuracy: 0.8842 - val_loss: 0.3933 - val_accuracy: 0.8658
Epoch 5/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3185 - accuracy: 0.8905 - val_loss: 0.3802 - val_accuracy: 0.8633
Epoch 6/100
50/50 [==============================] - 0s 2ms/step - loss: 0.3049 - accuracy: 0.8949 - val_loss: 0.3747 - val_accuracy: 0.8658
Epoch 7/100
50/50 [==============================] - 0s 2ms/step - loss: 0.2969 - accuracy: 0.8987 - val_loss: 0.3760 - val_accuracy: 0.8734
Epoch 8/100
5

In [25]:

import numpy as np
from sklearn.metrics import confusion_matrix

# predecir las probabilidades para los datos de prueba
y_probs = model.predict(X_test)
y_pred = np.argmax(y_probs, axis=-1)
cm = confusion_matrix(y_test, y_pred)
print(cm)

13/13 [==============================] - 0s 1ms/step
[[ 32   2   6]
 [  4  91  20]
 [  1   8 231]]


In [26]:
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred, digits=4)
print(report)

              precision    recall  f1-score   support

           0     0.8649    0.8000    0.8312        40
           1     0.9010    0.7913    0.8426       115
           2     0.8988    0.9625    0.9296       240

    accuracy                         0.8962       395
   macro avg     0.8882    0.8513    0.8678       395
weighted avg     0.8960    0.8962    0.8943       395



In [27]:
# Save the model to a single file
model.save( './rna_unbalance_test4.keras', save_format='keras_v3')