In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

In [ ]:
# Carga de datos
data = pd.read_csv('../../Data/DR3/espectros_normalizados_SNG.csv')
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [ ]:
# División de datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [4]:
# Definición del modelo y entrenamiento
gbt = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=0)
gbt.fit(X_train, y_train)

GradientBoostingClassifier(random_state=0)

In [5]:
# Predicción y evaluación del modelo
y_pred = gbt.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Confusion matrix:\n", cm)

Accuracy: 0.9846938775510204
Confusion matrix:
 [[  25    3    8]
 [   1   66   17]
 [   2    8 2418]]


In [6]:
from sklearn.metrics import cohen_kappa_score, classification_report

print("Cohen's kappa: ", cohen_kappa_score(y_test,y_pred))
print()
print(classification_report(y_test, y_pred, labels=[1,2,3], digits=4))

Cohen's kappa:  0.8203765563316125

              precision    recall  f1-score   support

           1     0.8929    0.6944    0.7812        36
           2     0.8571    0.7857    0.8199        84
           3     0.9898    0.9959    0.9928      2428

    accuracy                         0.9847      2548
   macro avg     0.9133    0.8253    0.8646      2548
weighted avg     0.9840    0.9847    0.9841      2548

