In [2]:
import pandas as pd
import tensorflow as tf
import os

# Load the model

In [3]:
model = tf.keras.models.load_model('./rna_unbalance.keras')

# Classify all Remaining Red Giants

In [5]:
df_rg = pd.read_csv("../../datasets/RG-unbalanced-1500.csv")
df_rg = df_rg.drop(df_rg.columns[0], axis=1)

import numpy as np
from sklearn.metrics import confusion_matrix

# predecir las probabilidades para los datos de prueba
y_probs = model.predict(df_rg)
y_pred = np.argmax(y_probs, axis=-1)
cm = confusion_matrix([2 for _ in range(len(y_pred))], y_pred)
print(cm)

2114/2114 [==============================] - 3s 1ms/step
[[    0     0     0]
 [    0     0     0]
 [  251  1013 66382]]


## Classify  Planetary Nebulae Candidates

In [5]:
df_pn_can = pd.read_csv("../../datasets/NP_Candidate.csv")
df_pn_can = df_pn_can.drop(df_pn_can.columns[0], axis=1)

import numpy as np
from sklearn.metrics import confusion_matrix

# predecir las probabilidades para los datos de prueba
y_probs = model.predict(df_pn_can)
y_pred = np.argmax(y_probs, axis=-1)
cm = confusion_matrix([1 for _ in range(len(y_pred))], y_pred)
print(cm)

5/5 [==============================] - 0s 2ms/step
[[ 0  0  0]
 [14 86 46]
 [ 0  0  0]]


In [7]:
df_pn_can = pd.read_csv("../../datasets/NP_Candidate.csv")
df_pn_can.insert(0, 'label', y_pred)
df_pn_can.to_csv('./np-candidate.csv', index=False)

# Suspected Symbiotic Stars v1

In [7]:
import numpy as np
from sklearn.metrics import confusion_matrix

df_sus_sy = pd.read_csv("../../../new/candidate_symbiotic_stars_v1/normalized/Suspected_SY.csv", header=None)

# predecir las probabilidades para los datos de prueba
y_probs = model.predict(df_sus_sy)
y_pred = np.argmax(y_probs, axis=-1)
cm = confusion_matrix([0 for _ in range(len(df_sus_sy))], y_pred, labels=[0, 1, 2])
print(cm)

1/1 [==============================] - 0s 24ms/step
[[14  1  0]
 [ 0  0  0]
 [ 0  0  0]]


In [8]:
df_sus_sy_normalized = pd.read_csv("../../../new/candidate_symbiotic_stars_v1/calibrated_data/Suspected_SY.csv")

df5 = pd.DataFrame(y_probs)
df5 = df5.round(4)
df5['label'] = y_pred
df5.insert(0, 'source_id', df_sus_sy_normalized['source_id'])
df5

source_id       0       1       2  label
0   4687286621186701568  0.9918  0.0079  0.0003      0
1   4651824725526390016  0.9778  0.0221  0.0000      0
2   3321366590173335424  0.8583  0.0870  0.0548      0
3   5410876219867043072  0.9997  0.0003  0.0000      0
4   3575939163051304192  0.9941  0.0059  0.0000      0
5   5799841957262188928  0.8371  0.1629  0.0000      0
6   6204217186929931520  0.7493  0.2507  0.0000      0
7   5981389610704878336  0.9936  0.0064  0.0000      0
8   4571810378118789760  0.8106  0.0239  0.1655      0
9   5979217486808094720  0.9744  0.0252  0.0004      0
10  4061952680197028224  0.9728  0.0270  0.0002      0
11  4178943599222583808  0.0000  0.6425  0.3575      1
12  4038647942747847936  0.9961  0.0039  0.0000      0
13  2022999316661190272  0.9378  0.0550  0.0073      0
14  2013433148849034368  0.8861  0.0698  0.0441      0

In [9]:
df6 = pd.read_csv('../../../new/candidate_symbiotic_stars_v1/built_dataset/suspected_SY_dataset.csv')
df6

FIND_NAME        MAIN_ID         OTYPE   SP_TYPE  \
0      RAW 1691        LIN 521            C*         C   
1    [BE74] 583     [BE74] 583  LongPeriodV*     G/Ke:   
2       StHA 55  EM* StHA   55          Mira       NaN   
3        ZZ CMi      V* ZZ CMi  LongPeriodV*  M6I-IIep   
4    WRAY 16−51     WRAY 16-51  LongPeriodV*        M4   
5     NSV 05572      V* VX Crv          Mira     M9III   
6        AE Cir      V* AE Cir        RCrBV*       NaN   
7      V748 Cen    V* V748 Cen        EclBin        Ae   
8      V345 Nor    V* V345 Nor          Mira    O-rich   
9      V934 Her    V* V934 Her  LongPeriodV*     M2III   
10   Hen 3−1383      THA 10-15       EmLine*       M3e   
11  WRAY 16−294    WRAY 16-294  LongPeriodV*        K5   
12       DT Ser      V* DT Ser          Star   F8III-V   
13     V618 Sgr    V* V618 Sgr        RCrBV*        Me   
14     V335 Vul    EM* AS  356            C*        Ce   
15     V627 Cas    EM* AS  501  LongPeriodV*  M2II-III   

                         ID_Gaia  \
0   Gaia DR2 4687286621186701568   
1   Gaia DR2 4651824725526390016   
2   Gaia DR3 3321366590173335424   
3   Gaia DR3 3155368612444708096   
4   Gaia DR2 5410876219860836224   
5   Gaia DR3 3575939163051304192   
6   Gaia DR3 5799841957262188928   
7   Gaia DR3 6204217186929931520   
8   Gaia DR3 5981389610704878336   
9   Gaia DR3 4571810378118789760   
10  Gaia DR2 5979217486808094720   
11  Gaia DR2 4061952680197028224   
12  Gaia DR3 4178943599222583808   
13  Gaia DR3 4038647942747847936   
14  Gaia DR3 2022999316661190272   
15  Gaia DR3 2013433148849034368   

                                                  IDS  \
0   RAW 1691|LIN 521|2MASS J01183570-7242213|OGLE ...   
1   2MASS J05265014-7106350|EROS2-star lm058-2n-25...   
2   IRAS 05440+0642|ASAS J054642+0643.7|ASAS J0546...   
3   BD+09  1633|AN  306.1934|DO  2156|GCRV  4915|G...   
4   IRAS 09316-4621|AKARI-IRC-V1 J0933295-463450|D...   
5   NSV  5572|ASAS J122152-1353.2|ATO J185.4686-13...   
6   SV* HV  5112|GSC2 S21330229737|Hen 3-1025|2MAS...   
7   CD-32 10517|ALS 18924|CRTS J145936.6-332503|CS...   
8   NSV  7429|BAaDE ad3a-22685|IRAS 16030-5156|2MA...   
9   HD 154791|2A 1704+241|3A 1703+241|AG+24 1704|A...   
10  Hen 3-1383|GSC 07366-01210|IRAS 17172-3306|IRA...   
11  2MASS J17391381-2538050|DENIS J173913.8-253805...   
12  GSC 05096-01722|IRAS 17592-0126|2MASS J1801522...   
13  SV* HV  7203|AN  313.1933|2MASS J18075721-3629...   
14  C* 2728|ASAS J192314+2427.7|Case  452|CGCS 425...   
15  HIP 113373|EM* AS  501|EM* VES  949|GEN# +6.20...   

                                               OTYPES             Gaia DR3  
0                C*|Em*|LP*|LP*|Em*|MIR|NIR|*|C*?|LP?  4687286621186701568  
1                                    LP*|Em*|NIR|V*|*  4651824725526390016  
2   Mi*|LP*|V*|LP*|SB*|LP*|MIR|V*|Em*|NIR|*|C*?|IR...  3321366590173335424  
3                                 LP*|NIR|V*|*|IR|LP?  3155368612444708096  
4                             LP*|NIR|MIR|Em*|PN|*|IR  5410876219867043072  
5            LP*|Mi*|Mi*|AB*|LP*|NIR|V*|MIR|*|Mi?|Opt  3575939163051304192  
6                        pA*|CV*|Sy*|V*|RC*|Em*|NIR|*  5799841957262188928  
7                                EB*|Ro*|NIR|V*|Em*|*  6204217186929931520  
8             Mas|Mi*|Mi*|AB*|Mas|V*|NIR|*|IR|LP?|V*?  5981389610704878336  
9                 LP*|LXB|LXB|V*|NIR|*|IR|Opt|X|X|gam  4571810378118789760  
10                                   NIR|MIR|Em*|*|IR  5979217486808094720  
11                       LP*|PN|NIR|Em*|*|C*?|ISM|LP?  4061952680197028224  
12                              MIR|NIR|V*|*|*|IR|pA?  4178943599222583808  
13                               pA*|LP*|NIR|RC*|V*|*  4038647942747847936  
14  C*|Mi*|LP*|LP*|LP*|LP*|V*|EmO|NIR|MIR|C*|Em*|*...  2022999316661190272  
15  LP*|LP*|LP*|EmO|Em*|Mas|MIR|NIR|V*|*|IR|LP?|LP...  2013433148849034368

In [10]:
# Filtro de data frames
df_filtered = df6.merge(df5, left_on=['Gaia DR3'], right_on=['source_id'], how='inner', indicator=True)
df_filtered = df_filtered[df_filtered['_merge'] == 'both']
df_filtered = df_filtered.iloc[:, [0, 1, 7, 9, 10, 11, 12]]
df_filtered

FIND_NAME        MAIN_ID             Gaia DR3       0       1       2  \
0      RAW 1691        LIN 521  4687286621186701568  0.9918  0.0079  0.0003   
1    [BE74] 583     [BE74] 583  4651824725526390016  0.9778  0.0221  0.0000   
2       StHA 55  EM* StHA   55  3321366590173335424  0.8583  0.0870  0.0548   
3    WRAY 16−51     WRAY 16-51  5410876219867043072  0.9997  0.0003  0.0000   
4     NSV 05572      V* VX Crv  3575939163051304192  0.9941  0.0059  0.0000   
5        AE Cir      V* AE Cir  5799841957262188928  0.8371  0.1629  0.0000   
6      V748 Cen    V* V748 Cen  6204217186929931520  0.7493  0.2507  0.0000   
7      V345 Nor    V* V345 Nor  5981389610704878336  0.9936  0.0064  0.0000   
8      V934 Her    V* V934 Her  4571810378118789760  0.8106  0.0239  0.1655   
9    Hen 3−1383      THA 10-15  5979217486808094720  0.9744  0.0252  0.0004   
10  WRAY 16−294    WRAY 16-294  4061952680197028224  0.9728  0.0270  0.0002   
11       DT Ser      V* DT Ser  4178943599222583808  0.0000  0.6425  0.3575   
12     V618 Sgr    V* V618 Sgr  4038647942747847936  0.9961  0.0039  0.0000   
13     V335 Vul    EM* AS  356  2022999316661190272  0.9378  0.0550  0.0073   
14     V627 Cas    EM* AS  501  2013433148849034368  0.8861  0.0698  0.0441   

    label  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       0  
8       0  
9       0  
10      0  
11      1  
12      0  
13      0  
14      0

In [14]:
out_name = 'rna_unbalanced.csv'
out_dir = '../../../new/candidate_symbiotic_stars_v1/output'
if not os.path.exists(out_dir):
    os.mkdir(out_dir)

fullname = os.path.join(out_dir, out_name)
df_filtered.to_csv(fullname, header=True, index=False)

# Suspected Symbiotic Stars v2

In [17]:
import numpy as np
from sklearn.metrics import confusion_matrix

df_sus_sy = pd.read_csv("../../../new/candidate_symbiotic_stars_v2/normalized/Suspected_SY.csv", header=None)

# predecir las probabilidades para los datos de prueba
y_probs = model.predict(df_sus_sy)
y_pred = np.argmax(y_probs, axis=-1)
cm = confusion_matrix([0 for _ in range(len(df_sus_sy))], y_pred, labels=[0, 1, 2])
print(cm)

1/1 [==============================] - 0s 21ms/step
[[14  2  1]
 [ 0  0  0]
 [ 0  0  0]]


In [20]:
df_sus_sy_normalized = pd.read_csv("../../../new/candidate_symbiotic_stars_v2/calibrated_data/Suspected_SY.csv")

df5 = pd.DataFrame(y_probs)
df5 = df5.round(4)
df5['label'] = y_pred
df5.insert(0, 'source_id', df_sus_sy_normalized['source_id'])
df5

source_id       0       1       2  label
0   6204217186929931520  0.0395  0.9605  0.0000      1
1   4061952680197028224  0.9050  0.0802  0.0148      0
2    670455944074475008  0.6006  0.0688  0.3306      0
3   4068755633500598272  0.0359  0.0675  0.8966      2
4   2060829659152816768  0.1874  0.8111  0.0015      1
5   2061069597507185792  0.8199  0.1785  0.0017      0
6   2056853691965982720  0.8237  0.1762  0.0001      0
7   2166560763171926656  0.9218  0.0666  0.0116      0
8   2199020614163298688  0.8879  0.1121  0.0000      0
9   2207583404553554944  0.9017  0.0981  0.0003      0
10  4056399699798000896  0.8015  0.1253  0.0733      0
11  4056614345105863040  0.9379  0.0497  0.0124      0
12  4059477915655995136  0.9658  0.0286  0.0056      0
13  4065437955878489856  0.7448  0.0783  0.1770      0
14  4065368033805697024  0.9669  0.0287  0.0044      0
15  4066214520316895360  0.8491  0.1132  0.0376      0
16  5852529218799852288  0.9926  0.0074  0.0000      0

In [22]:
df6 = pd.read_csv('../../../new/candidate_symbiotic_stars_v2/built_dataset/suspected_SY_dataset.csv')
df6

FIND_NAME                   MAIN_ID  \
0                     V748 Cen               V* V748 Cen   
1                  WRAY 16-294               WRAY 16-294   
2       DASCH J075731.1+201735       ASAS J075731+2017.6   
3          ASAS J174600-2321.3       ASAS J174600-2321.3   
4     IPHASJ201550.96+373004.2           IRAS 20140+3720   
5     IPHASJ202058.52+380949.8           IRAS 20191+3800   
6     IPHASJ202947.93+355926.5           IRAS 20278+3549   
7     IPHASJ204713.69+463517.5              EM* UHA   23   
8     IPHASJ215628.47+571445.5              HBHA 5704-02   
9     IPHASJ231735.92+634506.4           IRAS 23154+6328   
10    IPHASJ203413.39+410157.9              [CPR2002] B7   
11    IPHASJ191017.43+065258.1           IRAS 19078+0647   
12  VPHASDR2J175320.4-295327.4                    SS 326   
13  VPHASDR2J175346.2-284826.6   2MASS J17534619-2848266   
14  VPHASDR2J172830.6-292124.5   2MASS J17283059-2921245   
15  VPHASDR2J181154.5-243536.2   2MASS J18115453-2435360   
16  VPHASDR2J181333.6-245225.0  VPHAS J181333.6-245225.0   
17  VPHASDR2J181123.2-241430.0              [KW2003]  95   
18  VPHASDR2J141301.4-653320.1              WRAY 15-1180   
19  VPHASDR2J165421.0-404248.0  VPHAS J165421.0-404248.0   

                     OTYPE SP_TYPE                       ID_Gaia  \
0                   EclBin      Ae  Gaia DR3 6204217186929931520   
1             LongPeriodV*      K5  Gaia DR2 4061952680197028224   
2             LongPeriodV*   M0III   Gaia DR2 670455944074475008   
3   LongPeriodV*_Candidate     F0I  Gaia DR2 4068755633500598272   
4   PlanetaryNeb_Candidate     NaN  Gaia DR2 2060829659152816768   
5   PlanetaryNeb_Candidate     NaN  Gaia DR2 2061069597507185792   
6                      YSO      B2  Gaia DR2 2056853691965982720   
7                  EmLine*    K/Me  Gaia DR2 2166560758862873600   
8                  EmLine*     NaN  Gaia DR2 2199020614163298688   
9                  EmLine*     NaN  Gaia DR2 2207583404553554944   
10                     YSO     NaN  Gaia DR2 2067762904595539584   
11                     YSO     NaN  Gaia DR2 4306306181461925888   
12            LongPeriodV*     NaN  Gaia DR3 4056399699798000896   
13  LongPeriodV*_Candidate     NaN  Gaia DR3 4056614345105863040   
14  LongPeriodV*_Candidate     NaN  Gaia DR2 4059477915655995136   
15  LongPeriodV*_Candidate     NaN  Gaia DR2 4065437955878489856   
16            LongPeriodV*     NaN  Gaia DR3 4065368033805697024   
17                 EmLine*     NaN  Gaia DR2 4066214520316895360   
18            LongPeriodV*     NaN  Gaia DR2 5852529218799852288   
19           YSO_Candidate     NaN                           NaN   

                                                  IDS  \
0   CD-32 10517|ALS 18924|CRTS J145936.6-332503|CS...   
1   2MASS J17391381-2538050|DENIS J173913.8-253805...   
2   2MASS J07573112+2017347|ASAS J075731+2017.6|DA...   
3   2MASS J17460018-2321163|ASAS J174600-2321.3|ER...   
4   2MASS J20155096+3730042|AKARI-IRC-V1 J2015509+...   
5   2MASS J20205852+3809498|AKARI-IRC-V1 J2020585+...   
6   UCAC2  44376724|HBHA 3704-06|IPHAS J202947.93+...   
7   EM* UHA   23|ATO J311.8070+46.5881|HBHA 4703-3...   
8   2MASS J21562847+5714454|HBHA 5704-02|IPHAS J21...   
9   2MASS J23173591+6345064|HBHA 6207-18|IPHAS J23...   
10  2MASS J20341338+4101578|IPHAS J203413.39+41015...   
11  2MASS J19101743+0652579|AKARI-IRC-V1 J1910174+...   
12  OGLE BLG-ELL-9909|OGLE BUL-SC3 327739|SS 326|V...   
13  2MASS J17534619-2848266|VPHAS J175346.2-284826...   
14  2MASS J17283059-2921245|TIC 89479014|VPHAS J17...   
15  2MASS J18115453-2435360|TIC 377345544|VPHAS J1...   
16  VPHAS J181333.6-245225.0|[KW2003]  98|Gaia DR3...   
17  2MASS J18112322-2414299|TIC 249402294|VPHAS J1...   
18  2MASS J14130135-6533200|UCAC4 123-118322|VPHAS...   
19                           VPHAS J165421.0-404248.0   

                          OTYPES             Gaia DR3  
0           EB*|Ro*|NIR|V*|Em*|*  6204217186929931520  
1   LP*|PN|NIR|Em*|*|

In [23]:
# Filtro de data frames
df_filtered = df6.merge(df5, left_on=['Gaia DR3'], right_on=['source_id'], how='inner', indicator=True)
df_filtered = df_filtered[df_filtered['_merge'] == 'both']
df_filtered = df_filtered.iloc[:, [0, 1, 7, 9, 10, 11, 12]]
df_filtered

FIND_NAME                   MAIN_ID             Gaia DR3  \
0                     V748 Cen               V* V748 Cen  6204217186929931520   
1                  WRAY 16-294               WRAY 16-294  4061952680197028224   
2       DASCH J075731.1+201735       ASAS J075731+2017.6   670455944074475008   
3          ASAS J174600-2321.3       ASAS J174600-2321.3  4068755633500598272   
4     IPHASJ201550.96+373004.2           IRAS 20140+3720  2060829659152816768   
5     IPHASJ202058.52+380949.8           IRAS 20191+3800  2061069597507185792   
6     IPHASJ202947.93+355926.5           IRAS 20278+3549  2056853691965982720   
7     IPHASJ204713.69+463517.5              EM* UHA   23  2166560763171926656   
8     IPHASJ215628.47+571445.5              HBHA 5704-02  2199020614163298688   
9     IPHASJ231735.92+634506.4           IRAS 23154+6328  2207583404553554944   
10  VPHASDR2J175320.4-295327.4                    SS 326  4056399699798000896   
11  VPHASDR2J175346.2-284826.6   2MASS J17534619-2848266  4056614345105863040   
12  VPHASDR2J172830.6-292124.5   2MASS J17283059-2921245  4059477915655995136   
13  VPHASDR2J181154.5-243536.2   2MASS J18115453-2435360  4065437955878489856   
14  VPHASDR2J181333.6-245225.0  VPHAS J181333.6-245225.0  4065368033805697024   
15  VPHASDR2J181123.2-241430.0              [KW2003]  95  4066214520316895360   
16  VPHASDR2J141301.4-653320.1              WRAY 15-1180  5852529218799852288   

         0       1       2  label  
0   0.0395  0.9605  0.0000      1  
1   0.9050  0.0802  0.0148      0  
2   0.6006  0.0688  0.3306      0  
3   0.0359  0.0675  0.8966      2  
4   0.1874  0.8111  0.0015      1  
5   0.8199  0.1785  0.0017      0  
6   0.8237  0.1762  0.0001      0  
7   0.9218  0.0666  0.0116      0  
8   0.8879  0.1121  0.0000      0  
9   0.9017  0.0981  0.0003      0  
10  0.8015  0.1253  0.0733      0  
11  0.9379  0.0497  0.0124      0  
12  0.9658  0.0286  0.0056      0  
13  0.7448  0.0783  0.1770      0  
14  0.9669  0.0287  0.0044      0  
15  0.8491  0.1132  0.0376      0  
16  0.9926  0.0074  0.0000      0

In [24]:
out_name = 'rna_unbalanced.csv'
out_dir = '../../../new/candidate_symbiotic_stars_v2/output'
if not os.path.exists(out_dir):
    os.mkdir(out_dir)

fullname = os.path.join(out_dir, out_name)
df_filtered.to_csv(fullname, header=True, index=False)