In [2]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [3]:
# Cargamos los datos
data = pd.read_csv('../../Data/DR3/espectros_normalizados_balanceados_SNG.csv')

# Separamos las características y la variable objetivo
X = data.drop(data.columns[-1], axis=1)
y = data.iloc[:, -1]

In [4]:
# Creamos el modelo de clasificación Bayesiano
gnb = GaussianNB()

# Realizamos la validación cruzada con 5 particiones
scores = cross_val_score(gnb, X, y, cv=5)

# Mostramos los resultados
print('Precisión: %0.2f (+/- %0.2f)' % (scores.mean(), scores.std() * 2))

Precisión: 0.77 (+/- 0.04)


In [5]:
# Dividimos los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creamos el modelo de clasificación de Naive Bayes
nb = GaussianNB()

# Entrenamos el modelo utilizando el conjunto de entrenamiento
nb.fit(X_train, y_train)

# Hacemos predicciones en el conjunto de prueba
y_pred = nb.predict(X_test)

In [6]:
# Calculamos la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print('Precisión del modelo:', accuracy)

Precisión del modelo: 0.7677100494233937


In [7]:
from sklearn.metrics import confusion_matrix

# Predicción y evaluación del modelo
y_pred = nb.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Confusion matrix:\n", cm)

Accuracy: 0.7677100494233937
Confusion matrix:
 [[149  20  46]
 [ 22 158  25]
 [ 27   1 159]]


In [8]:
from sklearn.metrics import cohen_kappa_score, classification_report

print("Cohen's kappa: ", cohen_kappa_score(y_test,y_pred))
print()
print(classification_report(y_test, y_pred, labels=[1,2,3], digits=4))

Cohen's kappa:  0.6523312778766239

              precision    recall  f1-score   support

           1     0.7525    0.6930    0.7215       215
           2     0.8827    0.7707    0.8229       205
           3     0.6913    0.8503    0.7626       187

    accuracy                         0.7677       607
   macro avg     0.7755    0.7713    0.7690       607
weighted avg     0.7776    0.7677    0.7684       607

