In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [2]:
# Cargamos los datos
data = pd.read_csv('../../new/datasets/unbalanced.csv', header=None)

# Separamos las características y la variable objetivo
X = data.drop(data.columns[-1], axis=1)
y = data.iloc[:, -1]

In [3]:
# Creamos el modelo de clasificación Bayesiano
gnb = GaussianNB()

# Realizamos la validación cruzada con 5 particiones
scores = cross_val_score(gnb, X, y, cv=5)

# Mostramos los resultados
print('Precisión: %0.2f (+/- %0.2f)' % (scores.mean(), scores.std() * 2))

Precisión: 0.83 (+/- 0.04)


In [4]:
# Dividimos los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Creamos el modelo de clasificación de Naive Bayes
nb = GaussianNB()

# Entrenamos el modelo utilizando el conjunto de entrenamiento
nb.fit(X_train, y_train)

# Hacemos predicciones en el conjunto de prueba
y_pred = nb.predict(X_test)

In [5]:
# Calculamos la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print('Precisión del modelo:', accuracy)

Precisión del modelo: 0.8531645569620253


In [6]:
from sklearn.metrics import confusion_matrix

# Predicción y evaluación del modelo
y_pred = nb.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Confusion matrix:\n", cm)

Accuracy: 0.8531645569620253
Confusion matrix:
 [[ 32   4   4]
 [ 11  93  11]
 [ 27   1 212]]


In [7]:
from sklearn.metrics import cohen_kappa_score, classification_report

print("Cohen's kappa: ", cohen_kappa_score(y_test,y_pred))
print()
print(classification_report(y_test, y_pred, labels=[1,2,3], digits=4))

Cohen's kappa:  0.7380965990282937

              precision    recall  f1-score   support

           1     0.4571    0.8000    0.5818        40
           2     0.9490    0.8087    0.8732       115
           3     0.9339    0.8833    0.9079       240

    accuracy                         0.8532       395
   macro avg     0.7800    0.8307    0.7877       395
weighted avg     0.8900    0.8532    0.8648       395

