In [9]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [10]:
# Cargamos los datos
data = pd.read_csv('../../Data/DR3/espectros_normalizados_SNG.csv')

# Separamos las características y la variable objetivo
X = data.drop(data.columns[-1], axis=1)
y = data.iloc[:, -1]

In [11]:
# Creamos el modelo de clasificación Bayesiano
gnb = GaussianNB()

# Realizamos la validación cruzada con 5 particiones
scores = cross_val_score(gnb, X, y, cv=5)

# Mostramos los resultados
print('Precisión: %0.2f (+/- %0.2f)' % (scores.mean(), scores.std() * 2))

Precisión: 0.85 (+/- 0.01)


In [12]:
# Dividimos los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creamos el modelo de clasificación de Naive Bayes
nb = GaussianNB()

# Entrenamos el modelo utilizando el conjunto de entrenamiento
nb.fit(X_train, y_train)

# Hacemos predicciones en el conjunto de prueba
y_pred = nb.predict(X_test)

In [13]:
# Calculamos la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print('Precisión del modelo:', accuracy)

Precisión del modelo: 0.8335949764521193


In [14]:
from sklearn.metrics import confusion_matrix

# Predicción y evaluación del modelo
y_pred = nb.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Confusion matrix:\n", cm)

Accuracy: 0.8335949764521193
Confusion matrix:
 [[  32   10    4]
 [   8   68   10]
 [ 374   18 2024]]


In [15]:
from sklearn.metrics import cohen_kappa_score, classification_report

print("Cohen's kappa: ", cohen_kappa_score(y_test,y_pred))
print()
print(classification_report(y_test, y_pred, labels=[1,2,3], digits=4))

Cohen's kappa:  0.299017126958544

              precision    recall  f1-score   support

           1     0.0773    0.6957    0.1391        46
           2     0.7083    0.7907    0.7473        86
           3     0.9931    0.8377    0.9088      2416

    accuracy                         0.8336      2548
   macro avg     0.5929    0.7747    0.5984      2548
weighted avg     0.9670    0.8336    0.8895      2548

