In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import classification_report, balanced_accuracy_score
from sklearn.model_selection import GridSearchCV

In [2]:
#Cargar el archivo que contiene los datos de los tres tipos de espectros
# (Simbioticas-1, Nebulosas-2, Gigantes Rojas-3)
# DESPUÉS DEL BALANCEO DE DATOS (1000 APROX. POR CADA UNO)

data = pd.read_csv('../../../Data/DR3/espectros_normalizados_balanceados_SNG.csv')

In [3]:
# Separamos las características y la variable objetivo

X = data.drop(data.columns[-1],  axis=1)
y = data.iloc[:, -1]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [5]:
# Creamos el modelo de clasificación de Random Forest
rf = RandomForestClassifier(n_estimators=500, random_state=42)
scores = cross_val_score(rf, X, y, cv=5)
print("Precisión: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Precisión: 0.93 (+/- 0.10)


In [7]:
# Entrenamos el modelo utilizando el conjunto de entrenamiento
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

In [8]:
#Obtención del número de árboles de clasificación

# definir el modelo de Random Forest
#rf = RandomForestClassifier(random_state=42)

# definir los parámetros de la cuadrícula de búsqueda
#param_grid = {'n_estimators': [50, 100, 200, 300, 400, 500]}

# realizar la búsqueda en cuadrícula utilizando validación cruzada de 5 pliegues
#grid_search = GridSearchCV(rf, param_grid=param_grid, cv=5, scoring='accuracy')
#grid_search.fit(X_train, y_train)

In [9]:
# imprimir los resultados de la búsqueda en cuadrícula
#print("Mejores hiperparámetros: ", grid_search.best_params_)
#print("Mejor puntuación de validación cruzada: {:.2f}".format(grid_search.best_score_))

# evaluar el modelo con los mejores hiperparámetros en el conjunto de prueba
#y_pred = grid_search.predict(X_test)
#accuracy = accuracy_score(y_test, y_pred)
#print("Exactitud en el conjunto de prueba: {:.2f}".format(accuracy))

In [10]:
#Matriz de confusión
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[191   4   4]
 [ 18 173  12]
 [  1   2 202]]


In [11]:
import csv
# Save as CSV
with open("cm_rf_balanced.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(cm)

In [10]:
print("Cohen's kappa: ", cohen_kappa_score(y_test,y_pred))
print()
print(classification_report(y_test, y_pred, labels=[1,2,3], digits=4))

Cohen's kappa:  0.8986817678478374

              precision    recall  f1-score   support

           1     0.9095    0.9598    0.9340       199
           2     0.9665    0.8522    0.9058       203
           3     0.9266    0.9854    0.9551       205

    accuracy                         0.9325       607
   macro avg     0.9342    0.9325    0.9316       607
weighted avg     0.9343    0.9325    0.9317       607

