In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV

In [3]:
#Cargar el archivo que contiene los datos de los tres tipos de espectros
# (Simbioticas-1, Nebulosas-2, Gigantes Rojas-3, Secuencia Principal-4)
# DESPUÉS DEL BALANCEO DE DATOS (1000 APROX. POR CADA UNO)

data = pd.read_csv('../../../Data/DR3/espectros_normalizados_balanceados_SNGV.csv')

In [4]:
# Separamos las características y la variable objetivo

X = data.drop(data.columns[-1],  axis=1)
y = data.iloc[:, -1]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [6]:
# Creamos el modelo de clasificación de Random Forest
rf = RandomForestClassifier(n_estimators=500, random_state=42)
scores = cross_val_score(rf, X, y, cv=5)
print("Precisión: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Precisión: 0.91 (+/- 0.09)


In [7]:
# Entrenamos el modelo utilizando el conjunto de entrenamiento
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

In [8]:
#Matriz de confusión
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[217   4   0   3]
 [ 10 163   3   7]
 [  2   2 180   4]
 [  5   2  10 197]]


In [9]:
print("Cohen's kappa: ", cohen_kappa_score(y_test,y_pred))
print()
print(classification_report(y_test, y_pred, labels=[1,2,3,4], digits=4))

Cohen's kappa:  0.9140300898772618

              precision    recall  f1-score   support

           1     0.9274    0.9688    0.9476       224
           2     0.9532    0.8907    0.9209       183
           3     0.9326    0.9574    0.9449       188
           4     0.9336    0.9206    0.9271       214

    accuracy                         0.9357       809
   macro avg     0.9367    0.9344    0.9351       809
weighted avg     0.9361    0.9357    0.9355       809



Tomar 5% de conjunto de validación