In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV

In [2]:
#Cargar el archivo que contiene los datos de los tres tipos de espectros
# (Simbioticas-1, Nebulosas-2, Gigantes Rojas-3) con DATOS COMPLETOS

data = pd.read_csv('../../../Data/DR3/espectros_normalizados_SNG.csv')

In [3]:
# Separamos las características y la variable objetivo

X = data.drop(data.columns[-1],  axis=1)
y = data.iloc[:, -1]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [5]:
# Creamos el modelo de clasificación de Random Forest
rf = RandomForestClassifier(n_estimators=500, random_state=42)
scores = cross_val_score(rf, X, y, cv=5)
print("Precisión: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

KeyboardInterrupt: 

In [16]:
# Entrenamos el modelo utilizando el conjunto de entrenamiento
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=500, random_state=42)

In [17]:
# Hacemos predicciones en el conjunto de prueba
y_pred = rf.predict(X_test)

#Matriz de confusión
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[  21    7    8]
 [   1   69   14]
 [   2    3 2423]]


In [18]:
print("Cohen's kappa: ", cohen_kappa_score(y_test,y_pred))
print()
print(classification_report(y_test, y_pred, labels=[1,2,3], digits=4))

Cohen's kappa:  0.8373648658506339

              precision    recall  f1-score   support

           1     0.8750    0.5833    0.7000        36
           2     0.8734    0.8214    0.8466        84
           3     0.9910    0.9979    0.9945      2428

    accuracy                         0.9863      2548
   macro avg     0.9131    0.8009    0.8470      2548
weighted avg     0.9855    0.9863    0.9854      2548



In [19]:
# Calculamos la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

Accuracy: 0.9862637362637363
